apiVersion: apps/v1
kind: Deployment
metadata:
 name: back-deployment
 namespace: msh-dev
spec:
 selector:
   matchLabels:
    type: back
 replicas: 1
 template:
   metadata:
     labels:
       type: back
   spec:
    containers:
    - name: container
      image: songhyeon/back:latest
      ports:
      - containerPort: 8000